### ISSUE TITLE
LOB_START and LOB_END are not properly rendered on the docs site

### ISSUE THREAD

**Issue by siler** [amzn/ion-docs#103]
See http://amzn.github.io/ion-docs/docs/text.html

I see the following for LOB_START and LOB_END:

```antlr
fragment LOB_START    : ';
fragment LOB_END      : ';
```

It's not clear to me how this file is derived from the grammar branch or I'd make a pull request. If it is a manual transcription I can submit one.

**Comment by tgregg** [comment]
Thanks for bringing this to our attention. We will work to fix the rendering issue. In the meantime, the grammar can be viewed here: http://amzn.github.io/ion-docs/grammar/IonText.g4.txt

**Comment by jonwilsdon** [comment]
Resolved by https://github.com/amzn/ion-docs/pull/110
