### ISSUE TITLE
skips double quotes when converts to text representation

### ISSUE THREAD

**Issue by 9il** [amzn/ion-docs#113]
Using ion-js  form at https://amzn.github.io/ion-docs/
 `{"name s": "foo"}` ->` {name s: foo}`
Expected
`{"name s": foo}`

**Comment by pbcornell** [comment]
The ion-js form at https://amzn.github.io/ion-docs/ now properly encloses field names within single quotes when needed.  `{"name s": "foo"}` now becomes `{'name s': "foo"}`.  Fieldnames are effectively symbols, and single quotes are used around symbols when needed; whereas double quotes enclose **all** _string_ values in Ion.

Thanks for noticing and raising this bug :)
