### ISSUE TITLE
Clarify spec requirements for overpadded positive zero decimals

### ISSUE THREAD

**Issue by PeytonT** [amzn/ion-docs#152]
(Broken out of https://github.com/amzn/ion-docs/issues/133#issuecomment-873636960 as a separate issues.)

The spec for [binary decimals](https://amzn.github.io/ion-docs/docs/binary.html#5-decimal) gives 

> If the value is 0. (aka 0d0) then L is zero, there are no length or representation fields, and the entire value is encoded as the single byte 0x50.

As was initially the case in https://github.com/amzn/ion-docs/issues/93, this can be interpreted as requiring that `0x50` is the only valid representation of `0d0`.

Should this likewise be reworded? It seems unlikely that this wording was intended to convey a requirement for binary decimals, but similar wording was not intended to convey a similar requirement for binary ints.

Support for the "`0x50` is required" reading comes from the fact that the equivalent wording for ints (before it was changed in https://github.com/amzn/ion-docs/issues/93) did not go so far as to explicitly mention the byte representation `0x20`.

Support for the "`0x50` is optional" reading comes from the [next section](https://amzn.github.io/ion-docs/docs/binary.html#6-timestamp) on Timestamps, which uses `0d0` as an example of a decimal value being represented with `exponent` and `coefficient` fields.

> The fraction_exponent and fraction_coefficient denote the fractional seconds of the timestamp ***as a decimal value***. The fractional seconds’ value is coefficient * 10 ^ exponent. It must be greater than or equal to zero and less than 1. A missing coefficient defaults to zero. Fractions whose coefficient is zero and exponent is greater than -1 are ignored. The following hex encoded timestamps are equivalent:
> ...
> ```
> 69 80 0F D0 81 81 80 80 80 80    // The same instant with 0d0 fractional seconds and implicit zero coefficient
> 6A 80 0F D0 81 81 80 80 80 80 00 // The same instant with 0d0 fractional seconds and explicit zero coefficient
> ```

This could be interpreted as an artifact of Timestamps needing to distinguish between the presence/absence of the fractional second component for precision reasons, but it implies that `80` and `80 00` are valid as a `representation` of `0d0`.

It could be that the *"... as a decimal value"* wording should not actually be understood as meaning a valid `representation` of a decimal value, but this seems to conflict with the fact that `fraction_exponent` is a `VarInt` and `fraction_coefficient` is an `Int`.

Because *"the fractional seconds' value... must be greater than or equal to zero"*, `fraction_coefficient` never needs to represent a negative integer, and could have been chosen to be a `UInt`. Because *"the fractional seconds' value... must be less than 1"*, `fraction_exponent` never needs to represent a positive number, and could have been chosen to be a `VarUInt`. 

The fact that less compact representations were chosen over more compact representations indicates that they were chosen to align with the `exponent [VarInt]` and `coefficient [Int]` of `decimal`, and that the *"... as a decimal value"* wording should be understood literally.

**Comment by tgregg** [comment]
> Should this likewise be reworded?

Yes, I believe we should follow the precedent set by #93 and allow non-compact representations of `0d0` (e.g. `0x52 0x80 0x00`). If we follow the timestamp example, then I guess `0x51 0x80` would also be valid.

**Comment by PeytonT** [comment]
Closed by merging of https://github.com/amzn/ion-docs/pull/153.
