### ISSUE TITLE
ION ints: "Give Ion a Try!" does not support everything from the docs

### ISSUE THREAD

**Issue by agobeaux** [amzn/ion-docs#167]
In https://amzn.github.io/ion-docs/docs/spec.html#int, an example shows that the following values are possible for an int in Ion:
```
0xFA_CE    // An int denoted in hexadecimal with underscores
0b0101     // An int denoted in binary
0b10_10_10 // An int denoted in binary with underscores
1_2_3      // An int with underscores
```

`0xFACE` and `123` are working, but not the ones above. So it seems there are at least two problems: the use of underscores, and the use of binary format. I guess this is only an error with the "Give Ion a Try!" tool, I am hoping so.
There might also be errors for other types, I did not check it.

Error seen: `Error:  invalid character after number.`

<img width="753" alt="GiveIonATry" src="https://user-images.githubusercontent.com/25912836/174607237-8ba734f8-c71b-4cb3-9c59-2cf2dcd26cb9.png">

**Comment by zslayton** [comment]
Hi, thanks for reporting this. You've encountered a pair of limitations in [the `ion-js` library](https://github.com/amzn/ion-js) upon which the "Give Ion a Try!" widget is built. Specifically: issues [#239](https://github.com/amzn/ion-js/issues/239) and [#240](https://github.com/amzn/ion-js/issues/240).
