### ISSUE TITLE
Discuss syntax for `[]*` and `...*`

### ISSUE THREAD

**Issue by toddjonker** [amzn/ion-docs#230]
Checking my understanding: `x [any]*` is allowed, but `x any...*` is not? I would expect `*` to be either optional or forbidden in both grouping modes. (I think I'd prefer forbidden?)

_Originally posted by @zslayton in https://github.com/amazon-ion/ion-docs/pull/224#discussion_r1197894068_

**Comment by popematt** [comment]
@toddjonker I think that #308 and #302 have obviated the need for this issue. Would you agree?

**Comment by toddjonker** [comment]
Agreed; closing.
