### ISSUE TITLE
Reconsider handling of no-text inputs to `make_string` / `make_symbol` 

### ISSUE THREAD

**Issue by toddjonker** [amzn/ion-docs#327]
The spec currently states that `make_string`
> Produces a non-null, unannotated string containing the concatenated content produced by the arguments. Nulls and annotations are discarded.

There's still some discussion, eg at https://github.com/amazon-ion/ion-tests/pull/100#discussion_r1630181823 

The spec also ignores `$0` and absent shared symbols.  See also https://github.com/amazon-ion/ion-docs/issues/324

BTW the case that gives me the most pause is with one null, eg `(make_symbol null.string)` which one might expect to return `null.symbol` not "".   That's fairly useless for E-expression invocation (you could just write the desired null directly), but in templates it enables coercing _any_ string to a symbol.

**Comment by popematt** [comment]
Completed in #342. Passing nulls and symbols with unknown text to `make_string` or `make_symbol` must cause an error to be raised.
