### ISSUE TITLE
How does the `annotate` macro handle edge cases

### ISSUE THREAD

**Issue by popematt** [amzn/ion-docs#347]
What is the output of the following?
```
(:annotate (:: "a" "b") (:none))
```
Is it an error, or simply `(:none)`?

What about this?
```
(:annotate (:: "a" "b") (:values 1 2))
```
Is it an error, or is it `a::b::1  a::b::2`?

**Comment by toddjonker** [comment]
That should result in a cardinality error on the second parameter, which should be exactly-one.

On Thu, Oct 3, 2024, at 3:08 PM, Matthew Pope wrote:
> 
> 
> What is the output of the following?
> 
> `(:annotate (:: "a" "b") (:none))
`
> Is it an error, or simply `(:none)`?
> 
> What about this?
> 
> `(:annotate (:: "a" "b") (:values 1 2))
`

**Comment by popematt** [comment]
In #342, it says that the `value` parameter must be exactly one.
