### ISSUE TITLE
Clarify spec to allow overpadded zero integers.

### ISSUE THREAD

**Issue by tgregg** [amzn/ion-docs#93]
Currently, the spec states

> If the value is zero then T must be 2, L is zero, and there are no length or magnitude subfields.

This can be interpreted that `0x20` is the only valid representation of integer `0`. However, overpadded representations (e.g. `0x21 0x00`) should also be allowed. I suggest wording like:

"If the value is zero then T must be 2 and L may be zero with no length or magnitude subfields."

**Comment by PeytonT** [comment]
As the raiser of this specification issue, I can attest to its non-hypothetical nature. I have been working on a binary Ion parser in Rust from the specification and had implemented a [parsing error](https://github.com/PeytonT/serde_ion/commit/b5df8e8678c0ce9215b5ca18619e81e84cc39e7f#diff-9a269209bed069ffb36d5565a91c9840 ) for representations of zero other than `0x20` prior to learning that this was an error in the specification.

> "If the value is zero then T must be 2 and L may be zero with no length or magnitude subfields."

Recognizing that the implementation of the 4 Ion team supported parsers form something of a de facto standard superseding the specification, I think it's worth raising the point that the fix as proposed is technically a breaking change. A parser implemented against the Ion 1.0 spec as written will mis-parse `0x21 0x00` as invalid going forward.

To avoid making a breaking change I suggest instead to make the behavior optional at the level of the parser implementation, with whichever direction as the recommendation.

There are already at least two places in the spec with implementation-determined behavior.
[Optional reordering of fields in structs.](http://amzn.github.io/ion-docs/docs/spec.html#struct)
[Use of symbol ID zero for the name of fields in binary structs with NOP pad values.](http://amzn.github.io/ion-docs/docs/binary.html#13-struct)
There are likely a few more, but these two were easy to find.
There's also the matter of the non-uniform and de facto implementation defined maximum values and maximum sizes discussed in #79.

**Comment by tgregg** [comment]
When we make changes to the spec, we always have to assess the risk. In this case, the proposal is to be more permissive of what binary Ion parsers accept. This is inherently low-risk to the user because all existing data will continue to be parsed successfully. This would only break the user if they were depending on overpadded zero-valued integers being *rejected* by the parser. This is highly unlikely for a few reasons:
1. It is hard to imagine a use case for expecting failure for a specific uncommon encoding of a single value for a single type.
2. There are no known Ion generators that will *write* an overpadded zero-valued integer. Exercising this case would require users to write binary Ion by hand, which I expect is exceedingly rare except in unit tests of Ion reader/writer implementations.

As you point out, this will break parser implementations that treat overpadded zero-valued integers as illegal. That's fine; as library owners we expect to discover and fix limitations in the libraries over time. The ion-tests suite is the best mechanism we currently have to drive consistency between implementations. When this spec change is made, it should be accompanied by an additional `good/` file containing overpadded zero-valued integers in binary Ion.

**Comment by PeytonT** [comment]
No disagreement on the points, the question arises from uncertainty about the strictness of Ion's versioning commitments. There's no perfect answer. Ion has a versioning system, and the change is a breaking change, so one answer could be to bump up to Ion 1.1, but that seems like wild overkill. Another option is to introduce inconsistency and grace both the spec as written and the behavior of the core parsers as valid, undesirable on account of the inconstancy, but not a breaking change. Another option is to update the spec to match the core parsers, which has the downside of being a breaking change but the upside of being very easy and probably very safe. 

There is another option, to not update the spec and instead update the core parsers. This is similarly safe  for most of the same reasons, but has the benefit of not being a change to the spec. 

Which option is best comes down to weighing tradeoffs. It seems like you are concerned more about the prospect of adding another axis of implementation skew than about the nominally breaking but in practice almost certainly safe change. I'll revise #96 to reflect this.

**Comment by tgregg** [comment]
Closing via #96
